name: Aprendiendo GitHub Actions
run-name: Estoy aprendiendo Github Actions
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run shell script
        run: bash hola-mundo.sh
